version: "3.3"  # optional since v1.27.0
services:
  mongo:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - ./mongo_data:/data/db

  scanner:
    build:
      context: ./gas_scanner
      dockerfile: Dockerfile
    environment:
      PROVIDER_ADDRESS: ${PROVIDER_ADDRESS}
      CHAIN_ID: ${CHAIN_ID}
      MONGO_DB_CONNECTION_STRING: mongodb://mongo:27017
      MONGO_DB_NAME: GasUsage

      AGGREGATOR_DELAY_START: 60
      AGGREGATOR_DELAY_SECONDS: 60
      
      COLD_START_BLOCK: ${COLD_START_BLOCK}
      
      WATCHDOG_START_AGGREGATOR: node dist/gas_scanner_aggregator.js
      WATCHDOG_START_SERVER: node dist/gas_scanner_server.js
      WATCHDOG_START_COMMAND: node dist/gas_scanner_main.js --fillMissingBlocks
      WATCHDOG_AFTER_KILL_DELAY_MS: 5000
      WATCHDOG_AFTER_START_DELAY_MS: 15000
      WATCHDOG_ALLOWED_SECONDS_BEHIND: 30
      WATCHDOG_CHECK_EVERY_MS: 250000      
      
      SERVER_LISTEN_PORT: 7888
      SERVER_CACHE_VALIDITY: 3000
    ports:
      - ${BACKEND_PORT}:7888

